export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGINED = 'USER_LOGINED'
export const STORAGE_KEY = "AFF_APP"
export const GET_CHOSEN = "GET_CHOSEN"
export const USER_INFO_FETCHED = "USER_INFO_FETCHED"
export const USER_ROLE_FETCHED = "USER_ROLE_FETCHED"
export const USER_INFO_UPDATED = "USER_INFO_UPDATED"
export const PM_NOTICE_FETCHED = "PM_NOTICE_FETCHED"
export const BILLING_LOGOUT = "BILLING_LOGOUT"

export const SET_ADVERTISER_ID = 'SET_ADVERTISER_ID'
export const SET_CATEGORY_ID = 'SET_CATEGORY_ID'
export const SET_CONVERSIONFLOW_ID = 'SET_CONVERSIONFLOW_ID'
export const SET_VALUE = 'SET_VALUE'
export const GET_COOKIE_HASH = 'GET_COOKIE_HASH'
export const OFFER_INFO_FETCHED = "OFFER_INFO_FETCHED"
export const OFFER_INFO_UPDATED = "OFFER_INFO_UPDATED"
export const AFFACCESS_INFO_FETCHED = "AFFACCESS_INFO_FETCHED"
export const ACTIVE_USER_INFO_FETCHED = "ACTIVE_USER_INFO_FETCHED"

export const SWICTH_INACT_FETCHED = 'SWICTH_INACT_FETCHED'
export const APP_INFO_FETCHED = "APP_INFO_FETCHED"


export const REFRESH_AFF_ACCESS = "REFRESH_AFF_ACCESS"

export const REFRESH_APP_ACCESS = "REFRESH_APP_ACCESS"
export const ADV_INFO_UPDATED = "ADV_INFO_UPDATED"
export const GET_UNREAD_MESSAGE = "GET_UNREAD_MESSAGE"

